name: hello-world-example
on:
  push:
env:
  LOCAL: 'MacOS'
jobs:
  use-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        
        with:
          node-version: '16.2.0'

      -
        name: Install repo dependencies
        run: yarn

      -
        name: Run script from repo
        run: yarn action
  say-hello:
    runs-on: ubuntu-latest
    steps:
      -
        name: Say Hello
        run: echo "Hello world!"
      -
        name: Do stuff
        run: |
          echo "Step 1..."
          echo "Step 2..."
          echo "Step 3..."
          echo "Triggered by: $GITHUB_EVENT_NAME"
      -
        name: Say Goodbye
        run: echo "Goodbye!"
      -
        name: Useful default vars
        run: |
          echo "Workflow name:  $GITHUB_WORKFLOW"
          echo "Workspace:      $GITHUB_WORKSPACE"
          echo "Event:          $GITHUB_EVENT_NAME"
          echo "SHA:            $GITHUB_SHA"
          echo "Ref:            $GITHUB_REF"
          echo "Local:          $LOCAL"
